### ISSUE TITLE
Does not compile on macOS 15.3.2

### ISSUE THREAD

**Issue by mperham** [iliabylich/ractors-playground#1]
```
error[E0432]: unresolved import `libc::sem_timedwait`
 --> src/sem.rs:4:76
  |
4 |     CLOCK_REALTIME, clock_gettime, sem_destroy, sem_init, sem_post, sem_t, sem_timedwait, sem_wait,
  |                                                                            ^^^^^^^^^^^^^
  |                                                                            |
  |                                                                            no `sem_timedwait` in the root
  |                                                                            help: a similar name exists in the module: `sem_trywait`
```

**Comment by iliabylich** [comment]
yep, I mentioned that POSIX semaphores are not cross-platform in my article

**Comment by iliabylich** [comment]
MacOS has [`os_unfair_lock`](https://developer.apple.com/documentation/os/os_unfair_lock) API that allows its users to lock-and-wait-if-locked without busy looping:

```c
extern void os_unfair_lock_lock(os_unfair_lock_t lock);
```

> This is a replacement for the deprecated OSSpinLock. This function doesn’t spin on contention, but instead waits in the kernel to be awoken by an unlock.

which sounds a lot like a kernel-driven semaphore.

**Comment by mperham** [comment]
Looks like the build also has an undocumented dependency on `cbindgen`.

**Comment by iliabylich** [comment]
Only if you need to change the code (e.g. for development, not to run it locally). `cbindgen` is needed to re-generate [`rust-atomics.h`](https://github.com/iliabylich/ractors-playground/blob/master/rust-atomics/rust-atomics.h) every time you change the interface of the Rust library.

**Comment by mperham** [comment]
It blocks me from running `just test` and the readme does not explain how to install it. Looks like `cargo install cbindgen` worked for me.

**Comment by iliabylich** [comment]
🤦 you are right. I've updated README, thanks

**Comment by mperham** [comment]
Another fix for macOS, use Ruby's `etc` instead of `/proc`:

```diff
+++ b/tests/helper.rb
@@ -2,6 +2,7 @@ require 'benchmark'
 require 'bundler/setup'
 require 'c_atomics'
 require 'stringio'
+require 'etc'
 
 if ENV['GC_STRESS']
   GC.stress = true
@@ -16,7 +17,7 @@ end
 
 Warning[:experimental] = false
 
-CPU_COUNT = `cat /proc/cpuinfo | grep processor | wc -l`.to_i
+CPU_COUNT = Etc.nprocessors #`cat /proc/cpuinfo | grep processor | wc -l`.to_i
 puts "CPU count: #{CPU_COUNT}"
```

**Comment by mperham** [comment]
Do you have any longer term plans in this area? I would love to build a cross-platform gem with ractor-safe data structures. Ractors really aren't usable right now due to their extreme usage constraints and this would make a huge difference in usability. I figure we'd need to provide Counter, Array, Hash and Queue and you've got much of that working.

**Comment by iliabylich** [comment]
> Do you have any longer term plans in this area?

No
